{% set name = "ap_features" %}
{% set version = "2023.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 8df8cac2abd37b01672aab50b12d4524561ff66ff990a56063a61b96fa896ee6

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv --no-deps"

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - matplotlib-base
    - numpy
    - scipy
    - tqdm
    - numba

test:
  imports:
    - ap_features

  requires:
    - pip

  commands:
    - pip check

about:
  home: https://github.com/ComputationalPhysiology/ap_features
  summary: Package to compute features of traces from action potential models
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: "Package to compute features of traces from action potential models"
  doc_url: https://computationalphysiology.github.io/ap_features
  dev_url: https://github.com/ComputationalPhysiology/ap_features

extra:
  recipe-maintainers:
    - finsberg
